# Generated by Django 2.2.15 on 2020-08-30 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_education_experience_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='interest',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
